# Copyright (c) 2026 onyks-os
# SPDX-License-Identifier: MIT

"""Tor configuration and torrc generation module."""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import Optional

from ttp.paths import resolve_optional

# Runtime paths (volatile, stored on tmpfs)
TOR_RUNTIME_DIR = Path("/run/tor/ttp")

# Persistent cache for Tor Entry Guards. This is the only path
# that survives reboots, reducing bootstrap from ~30s to ~3s.
TOR_CACHE_DIR = Path("/var/lib/tor/ttp")

logger = logging.getLogger("ttp")

PT_MAP = {
    "obfs4": {
        "binary": "obfs4proxy",
        "apt-get": "obfs4proxy",
        "dnf": "obfs4",
        "pacman": "obfs4proxy",
        "zypper": "obfs4proxy",
    },
    "meek_lite": {
        "binary": "obfs4proxy",
        "apt-get": "obfs4proxy",
        "dnf": "obfs4",
        "pacman": "obfs4proxy",
        "zypper": "obfs4proxy",
    },
    "snowflake": {
        "binary": "snowflake-client",
        "apt-get": "snowflake-client",
        "dnf": "snowflake-client",
        "pacman": "snowflake-client",
        "zypper": "snowflake-client",
    },
}


def _build_torrc_content(
    tor_user: str,
    transport_port: int,
    dns_port: int,
    block_doh: bool,
    use_bridges: bool,
    bridges: list[str] | None,
    ipv6_avail: bool,
) -> str:
    """Build and return the string content for the volatile torrc file.

    This is a **pure function** with no side-effects, used to generate
    the torrc configuration dynamically based on the input options.

    Args:
        tor_user: System user running the Tor daemon.
        transport_port: Local TCP port for Tor TransPort redirection.
        dns_port: Local UDP/TCP port for Tor DNSPort redirection.
        block_doh: If True, maps canary DoH domains to 0.0.0.0.
        use_bridges: If True, enables Tor bridges.
        bridges: Optional list of bridge configuration strings.
        ipv6_avail: Whether IPv6 is enabled and supported on loopback.

    Returns:
        str: Rendered torrc configuration content.
    """
    lines = [
        "# Generated by TTP: runtime volatile config",
        "VirtualAddrNetworkIPv4 10.192.0.0/10",
        "AutomapHostsOnResolve 1",
        f"TransPort {transport_port}",
        f"DNSPort {dns_port}",
        "SocksPort 0",
        "ControlSocket /run/tor/ttp/control.sock",
        "ControlSocketsGroupWritable 1",
        "CookieAuthentication 1",
        f"CookieAuthFile {TOR_RUNTIME_DIR / 'auth_cookie'}",
        "CookieAuthFileGroupReadable 1",
        "ClientUseIPv4 1",
    ]

    if ipv6_avail:
        lines.extend(
            [
                f"TransPort [::1]:{transport_port}",
                f"DNSPort [::1]:{dns_port}",
                "ClientUseIPv6 1",
                "VirtualAddrNetworkIPv6 fc00::/7",
            ]
        )
    else:
        lines.append("ClientUseIPv6 0")

    lines.extend(
        [
            f"DataDirectory {TOR_CACHE_DIR}",
        ]
    )
    if block_doh:
        doh_domains = [
            "use-application-dns.net",  # Firefox canary
            "cloudflare-dns.com",
            "dns.google",
            "dns.quad9.net",
            "doh.opendns.com",
            "dns.adguard.com",
        ]
        for domain in doh_domains:
            lines.append(f"MapAddress {domain} 0.0.0.0")

    if use_bridges and bridges:
        lines.append("UseBridges 1")
        required_transports = []
        for b in bridges:
            parts = b.split()
            if parts:
                first_word = parts[0].lower()
                if first_word in PT_MAP and first_word not in required_transports:
                    required_transports.append(first_word)

        for pt in required_transports:
            binary = PT_MAP[pt]["binary"]
            # This path is written into torrc and Tor then *executes* it, so it
            # must come from the trusted lookup rather than from $PATH - a
            # PATH-derived value here would let a caller choose the program Tor
            # runs as the pluggable transport.
            binary_path = resolve_optional(binary)
            if binary_path:
                lines.append(f"ClientTransportPlugin {pt} exec {binary_path}")
            else:
                lines.append(f"ClientTransportPlugin {pt} exec /usr/bin/{binary}")

        for b in bridges:
            lines.append(f"Bridge {b}")

    if tor_user != "root":
        lines.append(f"User {tor_user}")

    return "\n".join(lines) + "\n"


def generate_torrc(
    tor_user: str,
    transport_port: int = 9041,
    dns_port: int = 9054,
    block_doh: bool = True,
    use_bridges: bool = False,
    bridges: Optional[list[str]] = None,
    disable_ipv6: bool = False,
) -> Path:
    """Generate a volatile ``torrc`` in ``/run/tor/ttp/torrc``.

    The ``DataDirectory`` points to the persistent cache (``/var/lib/tor/ttp``)
    so that Entry Guards are preserved across runs for fast bootstrapping.

    Args:
        tor_user: Username running the Tor process.
        transport_port: Local TCP port for Tor TransPort redirection.
        dns_port: Local UDP/TCP port for Tor DNSPort redirection.
        block_doh: If True, maps well-known DoH resolver domains to 0.0.0.0.
        use_bridges: If True, configures Tor to route via Pluggable Transports.
        bridges: Optional list of bridge lines (e.g. ``["obfs4 ...", "snowflake ..."]``).
        disable_ipv6: If True, forces IPv6 client routing off.

    Returns:
        Path: Absolute path to the generated ``torrc`` file.
    """
    TOR_RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    try:
        shutil.chown(TOR_RUNTIME_DIR, user=tor_user, group=tor_user)
    except (KeyError, ValueError, OSError):
        pass
    os.chmod(TOR_RUNTIME_DIR, 0o700)

    # Ensure parent directory of cache is owned by the Tor user and has correct permissions
    parent_dir = TOR_CACHE_DIR.parent
    if parent_dir.exists():
        try:
            shutil.chown(parent_dir, user=tor_user, group=tor_user)
            os.chmod(parent_dir, 0o700)
        except (KeyError, ValueError, OSError):
            pass

    # Persistent cache directory must be fixed on every run
    data_dir = str(TOR_CACHE_DIR)
    os.makedirs(data_dir, exist_ok=True)
    try:
        shutil.chown(data_dir, user=tor_user)
    except (KeyError, ValueError, OSError):
        pass
    os.chmod(data_dir, 0o700)

    from ttp.tor_detect import is_ipv6_supported

    ipv6_avail = is_ipv6_supported() and not disable_ipv6

    torrc_content = _build_torrc_content(
        tor_user=tor_user,
        transport_port=transport_port,
        dns_port=dns_port,
        block_doh=block_doh,
        use_bridges=use_bridges,
        bridges=bridges,
        ipv6_avail=ipv6_avail,
    )

    torrc_path = TOR_RUNTIME_DIR / "torrc"
    torrc_path.write_text(torrc_content, encoding="utf-8")
    try:
        os.chmod(torrc_path, 0o600)
    except OSError:
        pass
    logger.info("Generated runtime torrc at %s", torrc_path)
    return torrc_path
